sudo: required
language: java
dist: trusty
services:
  - docker
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - oraclejdk8
  - oraclejdk9

before_install:
  - export TZ=Asia/Shanghai
  - docker-compose up -d

script:
  - mvn -B -X clean package --file pom.xml
  - mvn -B clean verify -Dmaven.skip.integration=false
  - echo "benchmark TODO"



