name: benchmark

on:
  push:
    branches: [ master, 2.4 ]
  pull_request:
    branches: [ master, 2.4 ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Start clickhouse-server
        run: docker-compose up -d
      - name: Run benchmarks
        run: mvn -B -Pbenchmark clean integration-test -DskipITs
