name: benchmark

on:
  push:
    branches:
      - "master"
      - "2.4"
      - "2.5"
  pull_request_target:
    branches:
      - "master"
      - "2.4"
      - "2.5"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: sed -i 's/TRACE/INFO/g' clickhouse-native-jdbc/src/test/resources/simplelogger.properties
      - run: sed -i 's/DEBUG/INFO/g' clickhouse-native-jdbc/src/test/resources/simplelogger.properties

      - name: Run benchmarks
        run: |
          mvn -B -Pbenchmark clean integration-test -DskipITs -pl :clickhouse-native-jdbc -am | tee output.log
          echo "BENCHMARK_REPORT<<EOF" >> $GITHUB_ENV
          echo "`cat output.log | grep -E '^Benchmark\s.*\sUnits$' -A 100 | grep -E '.*\s(Units|ms/op)$'`" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: PR Comment
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            <details>
              <summary>BENCHMARK_REPORT</summary>

            ```
            ${{ env.BENCHMARK_REPORT }}
            ```
            </details>
