name: integration-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Start clickhouse-server
        run: docker-compose up -d
      - name: set up LOCAL to POSIX
        run:  |
            export LC_ALL=POSIX
            export LANG=POSIX
            export LANGUAGE=POSIX

      - name: Run integration-tests with maven
        run:  mvn -B clean verify -Dmaven.skip.integration=false
